production:
  adapter: postgresql
  database: <%= ENV.fetch("REDMINE_DB_DATABASE") %>
  host: <%= ENV.fetch("REDMINE_DB_POSTGRES") %>
  username: <%= ENV.fetch("REDMINE_DB_USERNAME") %>
  password: <%= ENV.fetch("REDMINE_DB_PASSWORD") %>
  encoding: utf8
